language: c
compiler:
    - clang
    - gcc
install:
    - sudo apt-get install -y libcurl cmake
before_script:
    - wget https://github.com/akheron/jansson/archive/master.zip -O /tmp/jansson.zip
    - cd /tmp/ && unzip jansson.zip
    - cd /tmp/jansson-master/ && autoreconf -i && ./configure && make && make install
script: cmake . && make